Sprint 12 new user info loading logic
roma685235423/ImageFeed pull request #13
Opened 2023-02-05 18:09 UTC by roma685235423

Приветствую, уважаемый проверяющий! В своей реализации я изменил порядок перехода от SplashViewController к TabBarViewController ввиду того, что старое требование о показе ProcessHUD в купе с загрузкой данных пользователя, идёт вразрез новому требованию для анимации градиентов элементов интерфейса ProfileViewController, т.к. данные к моменту перехода на экран профиля 100% будут загружены. В связи с этим переход к ленте фото происходит без блокировки интерфейса при наличии bearer token. Бонусом к скорости входа при данной реализации является экономия драгоценных запросов, так как данные профиля загружаются по мере необходимости. Эти изменения согласованы с наставниками:

Роман Бойко
Вчера, 21:34
Спринт 12/15: 12 → Тема 4/5: CoreAnimation → Урок 1/1
Всем привет! Подскажите, в чём смысл создания градиентов UILabel'ов на странице информации о пользователе? Ведь, насколько я помню, по ходу спринта не было речи об изменении последовательности перехода к TabBarViewController. ProcessHUD не скроется и переход на TabBarViewController не произойдёт до тех пор, пока данные, необходимые для наполнения этих лейблов, не будут получены. Может быть, судя по макету, нужно показывать градиент поверх фото и лэйблов до момента загрузки фото пользователя?

Денис Сурков
🍏
23:01
Рома, привет) Если ты про выполнение запроса для получения данных пользователя для экрана профиля, то в таком случае можно перенести выполнение этого запроса и выполнять его при открытии экрана профиля, а не на старте приложения. В таком случае будет актуально отображение этих градиентов. А еще так мы сделаем работу нашего приложения немного оптимальнее. Ведь пользователь может и не зайти на вкладку профиля, а мы в таком случае сделаем лишний запрос. Реализация такой логики будет особенно актуальна, когда у нас в приложении будет несколько табов 🙂

Роман Бойко
23:03
А ревьюэры примут мою работу?)))

Денис Сурков
🍏
23:05
а почему нет?) главное, все сделать согласно требованиям и, при необходимости, аргументировать свое решение 🙂

Роман Бойко
23:12
Тут требования противоречат друг другу: с одной стороны было требование показывать ProcessHUD и отложить переход на TabBarViewController до получения данных пользователя, с другой стороны есть требование анимировать градиент на время загрузки, которая к моменту отображения 100% будет завершена. Логичнее будет переделать часть с запросом.

Денис Сурков
🍏
23:14
Ты верно пишешь, да и лучше опираться на свежие требования при реализации

2023-02-06 18:36 UTC, IBDesignable requested changes

2023-02-06 18:36 UTC, IBDesignable commented on ImageFeed/Helpers/Formatter.swift
> +    }
В ТЗ авторы упоминают, что создание форматтеров дорогостоющая операция 

https://sarunw.com/posts/how-expensive-is-dateformatter/

И просят хранить только одну копию. Давай поправим, так чтобы дейтформаттер настроенный под одну из задач был создан всего раз

2023-02-06 18:36 UTC, IBDesignable commented on ImageFeed/ViewControllers/ProfileView/ProfileViewController.swift
> +        fetchProfile (token: token!)
:) а если токена не будет?) 

Давай не будем писать небезопасный код. Про то, когда можно, можно повдохновляться здесь
https://www.hackingwithswift.com/quick-start/understanding-swift/when-should-you-force-unwrap-optionals-in-swift

В остальных случаях код будет выглядеть в глазах проверяющего/нанимающего менеджера – грубо 
Лучше честно разыменовать
```
if let token = .... getToken() {
....
}
```

цепочка вызовов profileImageService.keychainWrapper – выглядит так, будто сервис профиля какой-то god object и из него можно делать что хочешь. Давай обращаться к dataStorage как отдельному самостоятельному сервису. Либо, в качестве альтернативы, ты можешь дописать интерфейс без доступа к свойству отсюда. 


Также, давай не будем расставлять пробелы перед аргументами:
```
         fetchProfile(token: token!)
       
```

2023-02-06 18:36 UTC, IBDesignable commented on ImageFeed/ViewControllers/ProfileView/ProfileViewController.swift
> +            self.profileImageService.cleanAvatarUrl()
очень круто продумано

2023-02-06 18:36 UTC, IBDesignable commented on ImageFeed/ViewControllers/ProfileView/ProfileViewController.swift
>                      return
а зачем здесь и ниже return?

2023-02-06 18:36 UTC, IBDesignable commented on ImageFeed/ViewControllers/ProfileView/ProfileViewController.swift
> +                        }
Очень тяжело читать такой код, давай выделим в функцию

2023-02-06 18:36 UTC, IBDesignable commented on ImageFeed/ViewControllers/ProfileView/ProfileViewController.swift
> +                return
эти ретерны избыточны

2023-02-06 18:36 UTC, IBDesignable commented on ImageFeed/ViewControllers/ProfileView/ProfileViewController.swift
> +                                return
guard case .success(let avatarURL) = result else { return } 

если не хочешь обрабатвыать второй кейс

2023-02-06 18:36 UTC, IBDesignable commented on ImageFeed/ViewControllers/SplashView/SplashViewController.swift
> +        if profileImageService.keychainWrapper.getBearerToken() != nil{
```suggestion
        if profileImageService.keychainWrapper.getBearerToken() != nil {

```

2023-02-06 18:36 UTC, IBDesignable commented on ImageFeed/ViewControllers/SplashView/SplashViewController.swift
>              UIBlockingProgressHUD.dismiss()
Лучше все-таки сначала дисмисить, затем презентить новое

2023-02-06 18:36 UTC, IBDesignable commented on ImageFeed/Services/ImagesListService/ImagesListService.swift
> +        let createdAt = Formatter.stringToDate(stringForConvertation: result.createdAt)
Почему-то в этом спринте пулреквест какой-то не полный, код как будто запушил не в эту ветку :( 
Оставить комментарии к нужным строкам не могу. Будь повнимательнее когда переходишь к новой задаче.

```swift
private func addNewPhotosToArray(photoResults: [PhotoResult]) {
        for photoResult in photoResults {
            let photo = self.convertPhotoResultToPhoto(result: photoResult)
            self.photos.append(photo)
        }
        NotificationCenter.default.post(
            name: ImagesListService.didChangeNontification,
            object: self
        )
    }
```

вот здесь функцию convertPhotoResultToPhoto можно поместить в расширение к PhotoResult (convertToViewModel) 

и тогда написать чуть попроще тогда  let newPhotos = photoResults.map { $0.convertToViewModel() }
и добавить photos.apend(contentOf: newPhotos)

2023-02-06 18:36 UTC, IBDesignable commented on ImageFeed/Services/ImagesListService/ImagesListService.swift
> +        let createdAt = Formatter.stringToDate(stringForConvertation: result.createdAt)
В подобных местах, я вижу что ты обнуляешь ссылку на задачу только в  одном из кейсов, а надо для любого из случаев
```
            DispatchQueue.main.async {
                switch result {
                case .success(let result):
                    self.lastLoadedPage = nextPage
                    self.addNewPhotosToArray(photoResults: result)
                    self.task = nil
                case .failure:
                    return
                }
            }
```

2023-02-06 18:36 UTC, IBDesignable commented on ImageFeed/Services/ImagesListService/ImagesListService.swift
> +        let createdAt = Formatter.stringToDate(stringForConvertation: result.createdAt)
Я не понимаю такую любовь к форс анврапам, когда свифт придумал столько способов сделать это безопасно!) 
Давай разучимся так писать :) 
```
 let nextPage = self.lastLoadedPage == nil
        ? 1
        : self.lastLoadedPage! + 1
``` 

Вот так будет в swifty-подходе:
```
var nextPage: Int 
if let lastLoadedPage {
  nextPage = lastLoadedPage + 1 
} else {
  nextPage = 1
}

```

2023-02-07 08:26 UTC, roma685235423 commented on ImageFeed/Helpers/Formatter.swift
> +    }
Интересная статья, буду знать, спасибо! Поправил)))

2023-02-07 08:27 UTC, roma685235423 commented on ImageFeed/ViewControllers/ProfileView/ProfileViewController.swift
> +        fetchProfile (token: token!)
Исправил.

2023-02-07 08:27 UTC, roma685235423 commented on ImageFeed/ViewControllers/ProfileView/ProfileViewController.swift
> +            self.profileImageService.cleanAvatarUrl()
Спасибо)))

2023-02-07 08:28 UTC, roma685235423 commented on ImageFeed/ViewControllers/ProfileView/ProfileViewController.swift
>                      return
А не на автомате написал) Убрал лишние return

2023-02-07 08:28 UTC, roma685235423 commented on ImageFeed/ViewControllers/ProfileView/ProfileViewController.swift
> +                        }
Сделал.

2023-02-07 08:29 UTC, roma685235423 commented on ImageFeed/ViewControllers/ProfileView/ProfileViewController.swift
> +                                return
Забыл вызвать аларм презентер.

2023-02-07 08:29 UTC, roma685235423 commented on ImageFeed/ViewControllers/SplashView/SplashViewController.swift
> +        if profileImageService.keychainWrapper.getBearerToken() != nil{
👌

2023-02-07 08:30 UTC, roma685235423 commented on ImageFeed/ViewControllers/SplashView/SplashViewController.swift
>              UIBlockingProgressHUD.dismiss()
Исправил.

2023-02-07 08:31 UTC, roma685235423 commented on ImageFeed/Services/ImagesListService/ImagesListService.swift
> +        let createdAt = Formatter.stringToDate(stringForConvertation: result.createdAt)
Поправил во всех случаях.

2023-02-07 08:31 UTC, roma685235423 commented on ImageFeed/Services/ImagesListService/ImagesListService.swift
> +        let createdAt = Formatter.stringToDate(stringForConvertation: result.createdAt)
Поправил. Буду иметь ввиду.

2023-02-07 08:56 UTC, roma685235423 commented on ImageFeed/Services/ImagesListService/ImagesListService.swift
> +        let createdAt = Formatter.stringToDate(stringForConvertation: result.createdAt)
Я запушил не в мастер, а в Sprint_12. Отдельную ветку создал, чтобы можно было вернуться к старой последовательности перехода к TabBar. Больше так не буду)

2023-02-07 20:27 UTC, IBDesignable commented on ImageFeed/Services/ImagesListService/ImagesListService.swift
> +        let createdAt = Formatter.stringToDate(stringForConvertation: result.createdAt)
Авторы тоже обещали поправить :) Прошу прощение за критику :)

2023-02-07 20:31 UTC, IBDesignable approved these changes

2023-02-07 20:31 UTC, IBDesignable commented on ImageFeed/Helpers/PhotoResult+Extension.swift
> +        )
селфы предпочтительно опускать

2023-02-07 20:31 UTC, IBDesignable commented on ImageFeed/Services/ImagesListService/ImagesListService.swift
> +        }
спасибо!

2023-02-07 20:31 UTC, IBDesignable commented on ImageFeed/Services/ImagesListService/ImagesListService.swift
>                      return
здесь return тоже можно убрать. 

дублирование с    self.task = nil избежать, если вызвать его после switch

2023-02-07 20:31 UTC, IBDesignable commented on ImageFeed/ViewControllers/ProfileView/ProfileViewController.swift
> +                    self.showDefaultAlertPresenter()
кажется все операции должны быть вызваны на главной очереди, но falure обрабатывается на той что пришла. 

Однако, на сколько я помню, у тебя все сетевые запросы возвращаются на главной, поэтому избыточно переводить на главную здесь. 

Давай перепроверим?

2023-02-07 21:00 UTC, roma685235423 commented on ImageFeed/Services/ImagesListService/ImagesListService.swift
>                      return
Сделал) и обрабатываю только .success, как ты показала)

2023-02-07 21:01 UTC, roma685235423 commented on ImageFeed/ViewControllers/ProfileView/ProfileViewController.swift
> +                    self.showDefaultAlertPresenter()
Исправил

2023-02-07 21:03 UTC, roma685235423 commented on ImageFeed/Services/ImagesListService/ImagesListService.swift
> +        }
Это тебе спасибо!

2023-02-07 21:03 UTC, roma685235423 commented on ImageFeed/Helpers/PhotoResult+Extension.swift
> +        )
Учёл

2023-02-07 21:04 UTC, roma685235423 commented on ImageFeed/Services/ImagesListService/ImagesListService.swift
> +        let createdAt = Formatter.stringToDate(stringForConvertation: result.createdAt)
Это весьма конструктивная и полезная критика, спасибо!

2023-02-07 21:09 UTC, merged