Sprint 13
roma685235423/ImageFeed pull request #16
Opened 2023-02-22 21:26 UTC by roma685235423

2023-02-24 09:31 UTC, protos17 requested changes

2023-02-24 09:31 UTC, protos17 commented on ImageFeed/ViewControllers/WebView/WebViewViewController.swift
>  fileprivate var progress = Float()
Не совсем понимаю для чего данная переменная и на будущее рекомендую переменные, к которым у нас имеет доступ разные классы выносить в отдельный файл с константами. Сейчас эта переменная нигде не используется и можно удалить

2023-02-24 09:31 UTC, protos17 commented on ImageFeed/Helpers/AuthHelper.swift
> +class AuthHelper: AuthHelperProtocol {
Давай проставлять ключевое слово `final` классам для ускорения работы компилятора.
Это нужно для оптимизация работы компилятора: ты явно сообщаешь о том, 
что класс не планируется расширять наследованием. 
В таком случае компилятор будет быстрее находить адрес ячейки памяти при вызове функции.

2023-02-24 09:31 UTC, protos17 commented on ImageFeed/Helpers/AuthHelper.swift
> +
Лишние отступы можно убрать, оставить только 1

2023-02-24 09:31 UTC, protos17 commented on ImageFeed/Helpers/AuthHelper.swift
> +           urlComponents.path == "/oauth/authorize/native",
Все пути лучше вынести в отдельную структуру

2023-02-24 09:31 UTC, protos17 commented on ImageFeed/Helpers/ProfileViewHelper.swift
> +        profileService.fetchProfile(token) { result in
Сильная ссылка, необходимо добавить weak

2023-02-24 09:31 UTC, protos17 commented on ImageFeed/ViewControllers/AuthView/AuthConfiguration.swift
> +            defaultBaseURL: DefaultBaseURL
Если убрать инициализатор, нужно будет поменять местами defaultBaseURL и authURLString

2023-02-24 09:31 UTC, protos17 commented on ImageFeed/ViewControllers/AuthView/AuthConfiguration.swift
> +    init(accessKey: String, secretKey: String, redirectURI: String, accessScope: String, authURLString: String, defaultBaseURL: URL) {
В структурах есть встроенный инициализатор, благодаря чему, не нужно его дополнительно писать. Его можно удалить

2023-02-24 09:31 UTC, protos17 commented on ImageFeed/ViewControllers/ImageList/ImagesListCell.swift
> +    private var imagesListCellImageGradient = CAGradientLayer()
Значение не меняется, можно установить как константу let

2023-02-24 09:31 UTC, protos17 commented on ImageFeed/ViewControllers/ProfileView/ProfileViewController.swift
> +class ProfileViewController: UIViewController & ProfileViewControllerProtocol {
Давай проставлять ключевое слово `final` классам для ускорения работы компилятора.
Это нужно для оптимизация работы компилятора: ты явно сообщаешь о том, 
что класс не планируется расширять наследованием. 
В таком случае компилятор будет быстрее находить адрес ячейки памяти при вызове функции.

2023-02-24 09:31 UTC, protos17 commented on ImageFeed/ViewControllers/ProfileView/ProfileViewController.swift
> +        DispatchQueue.main.async {
Сильная ссылка, необходимо написать weak

2023-02-24 09:31 UTC, protos17 commented on ImageFeed/ViewControllers/WebView/WebViewViewController.swift
> +public protocol WebViewViewControllerProtocol: AnyObject {
Public излишняя, достаточно internal

2023-02-24 09:31 UTC, protos17 commented on ImageFeed/ViewControllers/WebView/WebViewViewController.swift
> +    @IBOutlet  var webView: WKWebView!
Здесь стоит добавить `private`
Необходимо указывать private  для того, чтобы спрятать детали реализации конкретной части функциональности, 
когда они используются только внутри области объявления.

2023-02-24 09:31 UTC, protos17 commented on ImageFeedUITests/ImageFeedUITests.swift
> +        print(app.debugDescription)
Лишние принты перед коммитом строит убирать

2023-02-24 09:31 UTC, protos17 commented on ImageFeedUITests/ImageFeedUITests.swift
> +        app.alerts["Пока, пока!"].scrollViews.otherElements.buttons["Да"].tap()
Необходимо после этого добавить проверку, что мы вернулись на экран авторизации

2023-02-25 19:36 UTC, roma685235423 commented on ImageFeed/Helpers/AuthHelper.swift
> +class AuthHelper: AuthHelperProtocol {
Спасибо! Буду знать.

2023-02-25 19:36 UTC, roma685235423 commented on ImageFeed/Helpers/AuthHelper.swift
> +
Сделал.

2023-02-25 19:36 UTC, roma685235423 commented on ImageFeed/Helpers/ProfileViewHelper.swift
> +        profileService.fetchProfile(token) { result in
Сделал.

2023-02-25 19:37 UTC, roma685235423 commented on ImageFeed/ViewControllers/AuthView/AuthConfiguration.swift
> +            defaultBaseURL: DefaultBaseURL
Сделал.

2023-02-25 19:39 UTC, roma685235423 commented on ImageFeed/ViewControllers/AuthView/AuthConfiguration.swift
> +    init(accessKey: String, secretKey: String, redirectURI: String, accessScope: String, authURLString: String, defaultBaseURL: URL) {
Сделал.

2023-02-25 19:39 UTC, roma685235423 commented on ImageFeed/ViewControllers/ImageList/ImagesListCell.swift
> +    private var imagesListCellImageGradient = CAGradientLayer()
Сделал.

2023-02-25 19:40 UTC, roma685235423 commented on ImageFeed/ViewControllers/ProfileView/ProfileViewController.swift
> +class ProfileViewController: UIViewController & ProfileViewControllerProtocol {
Сделал. Спасибо за развёрнутое объяснение!

2023-02-25 19:40 UTC, roma685235423 commented on ImageFeed/ViewControllers/ProfileView/ProfileViewController.swift
> +        DispatchQueue.main.async {
Сделал.

2023-02-25 19:40 UTC, roma685235423 commented on ImageFeed/ViewControllers/WebView/WebViewViewController.swift
> +public protocol WebViewViewControllerProtocol: AnyObject {
Исправил.

2023-02-25 19:42 UTC, roma685235423 commented on ImageFeed/ViewControllers/WebView/WebViewViewController.swift
> +    @IBOutlet  var webView: WKWebView!
Добавил.

2023-02-25 19:42 UTC, roma685235423 commented on ImageFeedUITests/ImageFeedUITests.swift
> +        print(app.debugDescription)
Убрал.

2023-02-26 18:11 UTC, roma685235423 commented on ImageFeedUITests/ImageFeedUITests.swift
> +        app.alerts["Пока, пока!"].scrollViews.otherElements.buttons["Да"].tap()
Добавил.

2023-02-26 18:13 UTC, roma685235423 commented on ImageFeed/ViewControllers/WebView/WebViewViewController.swift
>  fileprivate var progress = Float()
Вроде бы я её удалял перед PR.

2023-02-26 18:25 UTC, roma685235423 commented on ImageFeed/Helpers/AuthHelper.swift
> +           urlComponents.path == "/oauth/authorize/native",
Сделал.

2023-02-27 14:37 UTC, protos17 approved these changes

2023-02-27 14:37 UTC, protos17 commented on ImageFeed/ViewControllers/AuthView/AuthConfiguration.swift
> +let UnsplashAuthorizeURLString = "https://unsplash.com/oauth/authorize"
Рекомендую данные константы переместить в файл Constants

2023-02-27 14:37 UTC, protos17 commented on ImageFeed/ViewControllers/WebView/WebViewViewController.swift
>      @IBAction func didTapBackButton(_ sender: Any?) {
Здесь стоит добавить `private`
Необходимо указывать private  для того, чтобы спрятать детали реализации конкретной части функциональности, 
когда они используются только внутри области объявления.

2023-02-27 14:37 UTC, protos17 commented on ImageFeed/Helpers/Constants.swift
> +    let like = "/like"
Рекомендую при выносе констант в отдельный файл прописывать их как static let ...

2023-02-27 14:37 UTC, protos17 commented on ImageFeed/Services/ImagesListService/ImagesListService.swift
>          guard let url = urlComponents.url else { fatalError("Failed to create URL") }
По своему опыту хотел бы отметить, что в продакшене не используют fatalError, советую заменить на assertionFailure.

2023-02-27 14:37 UTC, protos17 commented on ImageFeed/ViewControllers/WebView/WebViewPresenter.swift
> +internal protocol WebViewPresenterProtocol {
internal можно убрать

2023-02-27 14:37 UTC, protos17 commented on ImageFeed/ViewControllers/WebView/WebViewPresenter.swift
> +
Можно убрать лишние отступы

2023-02-27 14:37 UTC, protos17 commented on ImageFeed/Models/CustomErrors.swift
> +    internal var description: String {
internal можно убрать

2023-02-27 14:37 UTC, protos17 commented on ImageFeed/Models/CustomErrors.swift
> +    internal var errorDescription: String? {
internal можно убрать

2023-02-27 14:37 UTC, protos17 commented on ImageFeed/ViewControllers/WebView/WebViewViewController.swift
> +internal protocol WebViewViewControllerProtocol: AnyObject {
internal можно убрать

2023-02-27 20:00 UTC, merged