Sprint 10 o auth
roma685235423/ImageFeed pull request #6
Opened 2022-12-29 15:07 UTC by roma685235423

2022-12-30 15:25 UTC, mmbabaev commented
<img width="1123" alt="Screen Shot 2022-12-30 at 18 25 00" src="https://user-images.githubusercontent.com/12600807/210086394-b524926c-2023-4b5d-ba3b-6cf355e312f0.png">

2022-12-30 15:27 UTC, mmbabaev requested changes

2022-12-30 15:27 UTC, mmbabaev commented on ImageFeed/Models/OAuthTokenResponse.swift
> +    let access_token: String
так называть поля плохо. 

Можно использовать `CodingKeys`, чтобы писать имена через `camelCase`

Другой вариант - использовать `keyDecodingStrategy/keyEncodingStrategy` https://developer.apple.com/documentation/foundation/jsondecoder/keydecodingstrategy/convertfromsnakecase

2022-12-30 15:27 UTC, mmbabaev commented on ImageFeed/Resources/Assets.xcassets/Interface/nav_back_button.imageset/Contents.json
> +      "filename" : "chevron.backward@x1.png",
на 1x уже не нужно добавлять изображения, это совсем старые iphone 4s и младше

2022-12-30 15:27 UTC, mmbabaev commented on ImageFeed/Services/OAuth2.0/OAuth2Service.swift
> +    let UnsplashAuthorizePostURLString = "https://unsplash.com/oauth/token"
unsplashAuthorizePostURLString

2022-12-30 15:27 UTC, mmbabaev commented on ImageFeed/ViewControllers/AuthView/AuhtViewController.swift
> +            }
скачет форматирование. Предлагаю использовать `cmd+A` + `ctrl+I`

2022-12-30 15:27 UTC, mmbabaev commented on ImageFeed/ViewControllers/AuthView/Constants.swift
> +let AccessKey = "lHCFEGnBP871ogZAWrA69LFt22cYqyPvWoJxF6s9FjQ"
лучше занести константы в enum

2023-01-01 12:04 UTC, roma685235423 commented on ImageFeed/Resources/Assets.xcassets/Interface/nav_back_button.imageset/Contents.json
> +      "filename" : "chevron.backward@x1.png",
Спасибо, буду знать!

2023-01-01 12:05 UTC, roma685235423 commented on ImageFeed/ViewControllers/AuthView/Constants.swift
> +let AccessKey = "lHCFEGnBP871ogZAWrA69LFt22cYqyPvWoJxF6s9FjQ"
Тоже так думал сделать, но в задании сказано создать файл с константами. Переделал)))

2023-01-01 12:07 UTC, roma685235423 commented on ImageFeed/ViewControllers/AuthView/AuhtViewController.swift
> +            }
Обычно так и делаю перед коммитом. Скорее всего пропустил файл. Поправил.

2023-01-01 12:08 UTC, roma685235423 commented on ImageFeed/Services/OAuth2.0/OAuth2Service.swift
> +    let UnsplashAuthorizePostURLString = "https://unsplash.com/oauth/token"
Понял принял

2023-01-01 15:25 UTC, roma685235423 commented on ImageFeed/Models/OAuthTokenResponse.swift
> +    let access_token: String
Поправил.

2023-01-01 15:28 UTC, closed without merging